version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: task_master_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - task_master

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: task_master_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - task_master

  # Symfony apache project container
  www:
    build: docker/php
    container_name: task_master_php
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - task_master

networks:
  task_master:

volumes:
  db-data:
